export const ryanDetails = {
  "login":"DryFlyRyan",
  "id":13630604,
  "node_id":"MDQ6VXNlcjEzNjMwNjA0",
  "avatar_url":"https://avatars2.githubusercontent.com/u/13630604?v=4",
  "gravatar_id":"",
  "url":"https://api.github.com/users/DryFlyRyan",
  "html_url":"https://github.com/DryFlyRyan",
  "followers_url":"https://api.github.com/users/DryFlyRyan/followers",
  "following_url":"https://api.github.com/users/DryFlyRyan/following{/other_user}",
  "gists_url":"https://api.github.com/users/DryFlyRyan/gists{/gist_id}",
  "starred_url":"https://api.github.com/users/DryFlyRyan/starred{/owner}{/repo}",
  "subscriptions_url":"https://api.github.com/users/DryFlyRyan/subscriptions",
  "organizations_url":"https://api.github.com/users/DryFlyRyan/orgs",
  "repos_url":"https://api.github.com/users/DryFlyRyan/repos",
  "events_url":"https://api.github.com/users/DryFlyRyan/events{/privacy}",
  "received_events_url":"https://api.github.com/users/DryFlyRyan/received_events",
  "type":"User",
  "site_admin":false,
  "name":"Ryan Douglas",
  "company":"Lucky Dog Digital, LLC",
  "blog":"",
  "location":"Denver, CO",
  "email":null,
  "hireable":true,
  "bio":null,
  "twitter_username":null,
  "public_repos":116,
  "public_gists":2,
  "followers":31,
  "following":31,
  "created_at":"2015-08-03T19:29:35Z",
  "updated_at":"2020-09-23T00:45:58Z"
}

export const danDetails = {
  "login":"gaearon",
  "id":810438,
  "node_id":"MDQ6VXNlcjgxMDQzOA==",
  "avatar_url":"https://avatars0.githubusercontent.com/u/810438?v=4",
  "gravatar_id":"",
  "url":"https://api.github.com/users/gaearon",
  "html_url":"https://github.com/gaearon",
  "followers_url":"https://api.github.com/users/gaearon/followers",
  "following_url":"https://api.github.com/users/gaearon/following{/other_user}",
  "gists_url":"https://api.github.com/users/gaearon/gists{/gist_id}",
  "starred_url":"https://api.github.com/users/gaearon/starred{/owner}{/repo}",
  "subscriptions_url":"https://api.github.com/users/gaearon/subscriptions",
  "organizations_url":"https://api.github.com/users/gaearon/orgs",
  "repos_url":"https://api.github.com/users/gaearon/repos",
  "events_url":"https://api.github.com/users/gaearon/events{/privacy}",
  "received_events_url":"https://api.github.com/users/gaearon/received_events",
  "type":"User",
  "site_admin":false,
  "name":"Dan Abramov",
  "company":"@facebook ",
  "blog":"http://twitter.com/dan_abramov",
  "location":null,
  "email":null,
  "hireable":null,
  "bio":"Working on @reactjs. Co-author of Redux and Create React App. Building tools for humans.",
  "twitter_username":null,
  "public_repos":247,
  "public_gists":71,
  "followers":60323,
  "following":171,
  "created_at":"2011-05-25T18:18:31Z",
  "updated_at":"2020-09-19T23:06:31Z"
}